name: Minecraft Server CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add more steps to configure your server and deploy it
      # For example, installing Java, setting up dependencies, etc.
